### ISSUE TITLE
Sample Code Snippets 

### ISSUE THREAD

**Issue by Shubham-invent** [n0shake/Public-APIs#62]
Having a sample code snippets will be greatly helpful ,instead of going to the webpage and getting all the syntaxes from there.A sample Code snippet about using API will be of great help.

**Comment by Baneeishaque** [comment]
Please contribute to the repository by forking/cloning and creating
sample codes for the APIs in various languages.

On 1/19/17, Shubham-invent <notifications@github.com> wrote:
> Having a sample code snippets will be greatly helpful ,instead of going to
> the webpage and getting all the syntaxes from there.A sample Code snippet
> about using API will be of great help.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/abhishekbanthia/Public-APIs/issues/62


-- 
Banee Ishaque K

**Comment by GiacomoLaw** [comment]
This would be great, I'd love to see this! Maybe even linking to sample apps?

**Comment by abhishekbanthia** [comment]
That's an interesting idea. But since this is just a readme file, sample code snippets would take up a huge amounts of space making this repo almost unreadable. A more plausible thing I imagine is linking snippets in the API description. I'll keep this issue open for more discussion, let's hear from others.

**Comment by GiacomoLaw** [comment]
True

**Comment by bakman2** [comment]
You could also consider multiple documents - 1 main index and per topic a separate document with containing links+samplecode. Keeps it more managable/readable.

**Comment by abhishekbanthia** [comment]
That's sounds great. We can link both the docs which would make it manageable.

**Comment by GiacomoLaw** [comment]
I think it should be put into a separate folder, so there isn't a lot of .md files in the main repo.

**Comment by GiacomoLaw** [comment]
I've made a pr with a folder.

https://github.com/abhishekbanthia/Public-APIs/pull/70

**Comment by 007Cat24** [comment]
That is good idea and I agree with @GiacomoLaw . It would be a lot easier to try APIs. I would use Curl for them.

**Comment by Baneeishaque** [comment]
Best Rated Business Networking App

Hey abhishekbanthia/Public-APIs,

Get thousands of quality business leads for FREE and network with fellow
business owners on Feedwiser.

Best Regards,Banee Ishaque K

Accept Invite

Don't have the app yet? Download now for real-time notifications and more.

Sent by Feedwiser. 
If you wish to stop receiving email alerts, click on Unsubscribe.

**Comment by shockwavemoto** [comment]
Having a sample code snippets will be greatly helpful ,instead of going to the webpage and getting all the syntaxes from there.A sample Code snippet about using API will be of great help.
 :+1: 3  
You could also consider multiple documents - 1 main index and per topic a separate document with containing links+samplecode. Keeps it more managable/readable.
 :+1: 1  
that is good idea and I agree with @GiacomoLaw . It would be a lot easier to try APIs. I would use Curl for them.

**Comment by n0shake** [comment]
This is a nice idea, but collating and keeping the sample code up-to-date is a great maintenance burden! I'm happy to guide if someone wants to take this work on, otherwise we don't have the bandwidth to do this for existing APIs.
